name: CS102 Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pylint pytest-cov
        pip install -r homework06/requirements.txt
    - name: Run pylint
      run: |
        pylint --exit-zero homework07-web
    - name: Run mypy
      run: |
        mypy --version
        mypy homework07-web --ignore-missing --exclude "tests"
    - name: Run black
      run: |
        black --exclude "test*" homework07-web -l 100
